"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, LockKeyhole, Shield } from "lucide-react";

export default function LoginPage() {
  const [token, setToken] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const router = useRouter();
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); const response = await fetch("/api/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token }) }); const payload = await response.json().catch(() => ({})); setPending(false); if (!response.ok) { setError(payload.error || "Unable to sign in"); return; } router.replace("/"); router.refresh(); }
  return <main className="grid min-h-screen place-items-center p-5"><section className="surface w-full max-w-md rounded-3xl p-7 sm:p-9"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--accent)] text-[#06101e]"><Shield size={25}/></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.16em] text-[var(--accent)]">DigitDojo Shield</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Sign in to the console</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Enter the API token configured on your Shield daemon. It is verified server-side and stored only in a secure session cookie.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-medium">API token<input type="password" required value={token} onChange={(event) => setToken(event.target.value)} autoComplete="current-password" className="mt-2 w-full rounded-xl border border-[var(--border)] bg-[#09111d] px-3 py-3 outline-none focus:border-[var(--accent)]"/></label>{error && <p className="rounded-lg border border-[#ff718744] bg-[#ff718711] p-3 text-sm text-[var(--danger)]">{error}</p>}<button disabled={pending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-3 font-semibold text-[#06101e] disabled:opacity-60"><LockKeyhole size={17}/>{pending ? "Verifying…" : "Secure sign in"}<ArrowRight size={17}/></button></form></section></main>;
}
